### PR TITLE
dockerfile: Add isc-dhcp-server-ldap package

### PR DESCRIPTION
**Pull request by tonobo**

### CODE REVIEW

**Review by robinsmidsrod — CHANGES_REQUESTED** [review]
Please fix merge conflict and include information on why you want this extra package installed by default.

**Comment by tonobo** [comment]
Hey, branch has been rebased to master.

Why i wan't the additional packag?  I've a dynamic dhcp configuration ldap backed.

**Comment by robinsmidsrod** [comment]
As far as I can see, isc-dhcp-server-ldap replaces the /usr/sbin/dhcpd binary from the isc-dhcp-server package. This can cause unwanted changes for people that depend on this package because they most likely have different compilation settings. Some configurations might behave differently (which I assume is why it is built as a separate deb package).

If you can confirm through documentation from the Debian package documentation and ISC upstream about "no regressions" adding this I might be inclined to add it. The deb packages does state "Enhances: isc-dhcp-server", but the devil might be in the details on how that work.

Until I get any other information my recommendation is to either fork this project or create a new docker image that uses this image as base, but installs the ldap package version instead.

**Review by robinsmidsrod — APPROVED** [review]

**Comment by tonobo** [comment]
Oh, doesn't sound very well. I could build it at my own but isn't that cool. Is it an option to add another tag for it?

**Comment by robinsmidsrod** [comment]
Another tag could be a useful way to do it. Can you try to submit a pull request for this?

**Comment by tonobo** [comment]
Could you tell me how your deployment works?

**Comment by robinsmidsrod** [comment]
@tonobo I don't know how other people use this package, but it is important that the "latest" tag behaves the same way. I used to have automatic build setup in Docker Hub, but for some reason this has been disabled some time in the last year, probably because some feature I used in the GitHub/Docker Hub integration got deprecated or removed. My plan is to get this set up again so that commits to the master branch will trigger a rebuild of the "latest" tag on Docker Hub.

If we want an "ldap" or "ldap-latest" tag (probably just "ldap") then we can either use a different branch for it or some form of build variable to the Dockerfile indicating which version to build. I don't have a lot of experience with this, so if you have some experience, please assist in any way you can.

Right now I'm kind of stuck on the fact that I need a service account (in GitHub or Docker Hub) to ensure that the autobuild feature in Docker Hub doesn't use my personal oauth credentials for access to the git repo. If you know exactly how to setup this I would love some pointers.

**Comment by tonobo** [comment]
In my mind, it would be the best way to login to docker hub and connect the github organisation with docker hub. After connecting it's quite easy to setup a custom Dockerfile per bild. I prefer :ldap as tag as well. I'll update the PR but i'm unable to further help you by setting up the docker build pipeline. :(

**Comment by robinsmidsrod** [comment]
@tonobo I should have automated builds working again, and I was able to create an `ldap` tag as you wanted. It is quite ugly, because of all the code duplication, but it does work. If you have any ideas on how to avoid all the code duplication I would love to hear it. In Docker Hub automated build settings I've set build context to `/` for both tags, but one uses /Dockerfile and the other uses /Dockerfile.ldap. They are currently just copies of each other with the additional package installed in the ldap file.

**Comment by tonobo** [comment]
@robinsmidsrod Pretty cool! Regarding the code duplication, we might add a build arg for the dhcp package, but i'm not really sure if it's better than just coping.

**Pull request closed without merging**
